package xFuzzyHH;

//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_hervirHuevo_Tamanho                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Tamanho"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_hervirHuevo_Tamanho {
 private double min = 40.0;
 private double max = 70.0;
 private double step = 1.0344827586206897;
 double _ps_S1[] = { 40.0,9.0 };
 double _pl_S1[] = {  };
 double _ps_CE[] = { 55.0,9.0 };
 double _pl_CE[] = {  };
 double _ps_B1[] = { 70.0,9.0 };
 double _pl_B1[] = {  };
 MF_xfl_bell S1 = new MF_xfl_bell(min,max,step,_ps_S1,_pl_S1);
 MF_xfl_bell CE = new MF_xfl_bell(min,max,step,_ps_CE,_pl_CE);
 MF_xfl_bell B1 = new MF_xfl_bell(min,max,step,_ps_B1,_pl_B1);
}


