package xFuzzyHH;

//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_hervirHuevo_Tipo                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Tipo"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_hervirHuevo_Tipo {
 private double min = 1.0;
 private double max = 3.0;
 private double step = 1.0;
 double _ps_blando[] = { 1.0 };
 double _pl_blando[] = {  };
 double _ps_medio[] = { 2.0 };
 double _pl_medio[] = {  };
 double _ps_duro[] = { 3.0 };
 double _pl_duro[] = {  };
 MF_xfl_singleton blando = new MF_xfl_singleton(min,max,step,_ps_blando,_pl_blando);
 MF_xfl_singleton medio = new MF_xfl_singleton(min,max,step,_ps_medio,_pl_medio);
 MF_xfl_singleton duro = new MF_xfl_singleton(min,max,step,_ps_duro,_pl_duro);
}


