package xFuzzyHH;

//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_hervirHuevo_Tiempo                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Tiempo"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_hervirHuevo_Tiempo {
 private double min = 3.0;
 private double max = 6.0;
 private double step = 0.011764705882352941;
 double _ps_S2[] = { 2.5,3.0,3.5,4.0 };
 double _pl_S2[] = {  };
 double _ps_CE[] = { 4.0,4.5,5.0 };
 double _pl_CE[] = {  };
 double _ps_S1[] = { 3.5,4.0,4.5 };
 double _pl_S1[] = {  };
 double _ps_B1[] = { 4.5,5.0,5.5 };
 double _pl_B1[] = {  };
 double _ps_B2[] = { 5.0,5.5,6.0,6.5 };
 double _pl_B2[] = {  };
 MF_xfl_trapezoid S2 = new MF_xfl_trapezoid(min,max,step,_ps_S2,_pl_S2);
 MF_xfl_triangle CE = new MF_xfl_triangle(min,max,step,_ps_CE,_pl_CE);
 MF_xfl_triangle S1 = new MF_xfl_triangle(min,max,step,_ps_S1,_pl_S1);
 MF_xfl_triangle B1 = new MF_xfl_triangle(min,max,step,_ps_B1,_pl_B1);
 MF_xfl_trapezoid B2 = new MF_xfl_trapezoid(min,max,step,_ps_B2,_pl_B2);
}


